---

replicaCount: 1

env:
  STAGE_ENVIRONMENT: "DEV-ENVIRONMENT"
  
image:
  repository: 192.168.145.182/kargo/demo-app
  pullPolicy: IfNotPresent
  tag: 5.0.0

service:
  type: LoadBalancer
  port: 80
