---

replicaCount: 3

env:
  STAGE_ENVIRONMENT: "HCM-PRODUCTION"

image:
  repository: 192.168.145.182/kargo/demo-app
  pullPolicy: IfNotPresent
  tag: 4.0.0

service:
  type: LoadBalancer
  port: 80
