---

replicaCount: 4

env:
  STAGE_ENVIRONMENT: "HNI-PRODUCTION"

image:
  repository: 192.168.145.182/kargo/demo-app
  pullPolicy: IfNotPresent
  tag: 3.0.0

service:
  type: LoadBalancer
  port: 80
