---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "${K8S_PROJECT_NAME}"
  namespace: argocd
spec:
  description: "Project for ${K8S_PROJECT_NAME}"
  clusterResourceWhitelist:
    - group: "*"
      kind: Namespace
  destinations:
    - name: '*'
      namespace: "${K8S_PROJECT_NAME}-*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "${GH_DEV_URL}"
    - "${GH_CHART_URL}"

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "${K8S_PROJECT_NAME}"
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: "${GH_DEV_URL}"
      revision: main
      directories:
      - path: helm-values/*
  template:
    metadata:
      name: "${K8S_PROJECT_NAME}-{{path.basename}}"
      annotations:
        kargo.akuity.io/authorized-stage: "${K8S_PROJECT_NAME}:{{path.basename}}"
    spec:
      project: "${K8S_PROJECT_NAME}"
      sources:
      - repoURL: "${GH_CHART_URL}"
        targetRevision: main
        path: thanh-demo-app-py-chart
        helm:
          valueFiles:
            - values-{{path.basename}}.yml
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "${K8S_PROJECT_NAME}-{{path.basename}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true