---

replicaCount: 2

env:
  STAGE_ENVIRONMENT: "STG-ENVIRONMENT"
  
# image:
#   repository: dvanthanh1992/demo-app-py
#   pullPolicy: Always
#   tag: "8.0.0"

service:
  type: LoadBalancer
  port: 80
